### ISSUE TITLE
Is this part of the Apereo Incubation?

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/widget-creator#2]
Was this project split off from angulars-portal / uPortal-home because it is not part of the incubation, or to separate out a logically independent piece of code?

**Comment by vertein** [comment]
It's logically a stand alone app.  It also gives another example of using the uPortal App Framework to build out an app.

**Comment by apetro** [comment]
Broken out for better modularity.

I think it ends up being in-scope for the incubation and in the fullness of time it'll have more of the trappings of uPortal incubating project-ness. Committers file, documentation. Conceptually it's a module of uPortal-home. You got your uPortal-home as your portal homepage; you got your widget-creator to help create widgets for the uPortal-home. 

Will eventually get around to cleaning all this up. This will somehow relate to continuing to challenge uPortal as a project to get better at wrangling an ecosystem and accepting smaller and smaller modular pieces in that ecosystem.

**Comment by ChristianMurphy** [comment]
Could that relationship be documented similar to UW-Madison-DoIT/KeyValueStore/pull/18 ?

**Comment by ChristianMurphy** [comment]
:bell: [The new uPortal ecosystem intake process is live](https://groups.google.com/a/apereo.org/d/msg/uportal-dev/lhgtquVXZLM/-hB9iRNOAAAJ).
