### ISSUE TITLE
Enable Greenkeeper

### ISSUE THREAD

**Issue by ChristianMurphy** [UW-Madison-DoIT/widget-creator#23]
See https://github.com/uPortal-Project/uportal-home/issues/639 for motivation.

**Comment by ChristianMurphy** [comment]
:bell: @apetro @vertein

**Comment by vertein** [comment]
:+1:

**Comment by ChristianMurphy** [comment]
enabling greenkeeper requires an organization admin to flip the switch.
https://github.com/apps/greenkeeper

**Comment by apetro** [comment]
[Installed Greenkeeper](https://account.greenkeeper.io/account/UW-Madison-DoIT), I think. A Greenkeeper PR should appear at some point.
